name: Health check every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  api-check:
    runs-on: ubuntu-latest
    steps:
      - run: curl --request OPTIONS --url '${{ secrets.API_URL }}' --silent --output /dev/null --connect-timeout 0 --max-time 0
